### ISSUE TITLE
names of stop_positions aren't fetched from stop_area relation

### ISSUE THREAD

**Issue by DerDakon** [sb12/OSMTrainRouteAnalysis#2]
A stop_position does not need to have a name tag if it is place of a stop_area relation. On those nodes the name information is not fetched from the relation, but "unknown stop" is shown. Example S21 from Barsinghausen to Hanover.

**Comment by sb12** [comment]
Hi,
I'm aware of this issue. The problem is that I only fetch the elements that are in the route relation at the moment, so the programm does not have access to the stop area relation, it doesn't even know that it is there.
As a solution I need to find a way to fetch the stop area relations together with the route relation.
Any ideas how to achieve this are welcome.

**Comment by DerDakon** [comment]
Has the code on the website been updated? I still see the old behavior.

**Comment by sb12** [comment]
Sorry I forgot to update the code after this change. It should work now. Example: http://osmtrainroutes.bplaced.net/beta/?id=4435865&train=regional
